name: Tests

on: [push, pull_request]

jobs:
  tests:
    name: Reusable
    uses: ./.github/workflows/reusable-tests.yaml
    with:
      cache: true
      solana_cli_version: 1.14.16
      node_version: 17.0.1
      cargo_profile: debug
      anchor_binary_name: anchor-binary
